[workspace]
channels = ["conda-forge", "bioconda", "nodefaults"]
name = "ngs-trim"
platforms = ["linux-64"]
version = "0.5.6"

[tasks]

[dependencies]
snakemake = ">=9.0.1,<10"
snakemake-storage-plugin-http = ">=0.3.0,<1"
conda = ">=25.1.1,<26"

[environments]
test = { features = ["test"] }
format = { features = ["format"], no-default-feature = true }

[feature.test.dependencies]
pytest = "*"
graphviz = "*"

[feature.format.dependencies]
black = "*"
snakefmt = "*"
