
# - Only tested with Phred33 quality scores

#############
### READS ###
#############
trim:
  activate: true
  tool: adapterremoval
  params: "--mm 3 --trimns --maxns 20 --trimqualities --minquality 2 --minlength 30"

# Ignored for SE
collapse:
  activate: true
  params: "--collapse-conservatively --minalignmentlength 11"

report:
  multiqc: "--verbose"
