
# - Only tested with Phred33 quality scores

#############
### READS ###
#############
trim:
  activate: true
  tool: adapterremoval
  params: "--trimns --maxns 10 --trimqualities --minlength 30"

# Ignored for SE
collapse:
  activate: true
  params: "--collapse-conservatively"

report:
  multiqc: "--verbose"
